# Generated by Django 3.1.1 on 2020-09-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
    ]
